name: Docker hello world

inputs:
  who-to-greet:
    description: Who to greet in the log
    required: true
    default: 'world'
    type: string

outputs:
  time:
    description: 'The time we said hello'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
